name: edsuite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  flutter_gradient_colors: ^2.1.1
  go_router: ^16.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  edsuite_common:
    path: packages/edsuite_common

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700

  - family: Brunson
    fonts:
      - asset: fonts/brunson/Brunson.ttf
    
  - family: Movista
    fonts:
      - asset: fonts/movista-sans-serif/Mosvita-Light.ttf
        weight: 300
      - asset: fonts/movista-sans-serif/Mosvita-Regular.ttf
        weight: 400
      - asset: fonts/movista-sans-serif/Mosvita-SemiBold.ttf
        weight: 600
      - asset: fonts/movista-sans-serif/Mosvita-Bold.ttf
        weight: 700

  uses-material-design: true
